# Generated by Django 3.0.5 on 2020-05-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Tahun_Ajaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.IntegerField(null=True)),
                ('semester', models.CharField(choices=[('GANJIL', 'GANJIL'), ('GENAP', 'GENAP')], max_length=30, null=True)),
            ],
        ),
    ]
