# Generated by Django 3.0.5 on 2020-05-27 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tahun_ajaran', '0001_initial'),
        ('siswa', '0001_initial'),
        ('guru', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Data_Absen_Siswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jam', models.DateTimeField(auto_now_add=True)),
                ('siswa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='siswa.Data_Siswa')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absen.Status')),
                ('tahun_ajaran', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tahun_ajaran.Data_Tahun_Ajaran')),
            ],
        ),
        migrations.CreateModel(
            name='Data_Absen_Guru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jam', models.DateTimeField(auto_now_add=True)),
                ('guru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guru.Data_Guru')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absen.Status')),
                ('tahun_ajaran', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tahun_ajaran.Data_Tahun_Ajaran')),
            ],
        ),
    ]
