# Generated by Django 3.0.5 on 2020-05-27 11:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tahun_ajaran', '0001_initial'),
        ('siswa', '0001_initial'),
        ('guru', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulan_Pembayaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Jenis_Pembayaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_pembayaran', models.CharField(max_length=100)),
                ('tagihan', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Data_Pembayaran_UTS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Lunas', 'Lunas'), ('Belum Lunas', 'Belum Lunas')], default='Belum Lunas', max_length=255)),
                ('jenis_pembayaran', models.ForeignKey(limit_choices_to={'jenis_pembayaran': 'UTS'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Jenis_Pembayaran')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siswa.Data_Siswa')),
                ('tahun_ajaran', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tahun_ajaran.Data_Tahun_Ajaran')),
            ],
            options={
                'ordering': ['siswa'],
            },
        ),
        migrations.CreateModel(
            name='Data_Pembayaran_UAS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Lunas', 'Lunas'), ('Belum Lunas', 'Belum Lunas')], default='Belum Lunas', max_length=255)),
                ('jenis_pembayaran', models.ForeignKey(limit_choices_to={'jenis_pembayaran': 'UAS'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Jenis_Pembayaran')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siswa.Data_Siswa')),
                ('tahun_ajaran', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tahun_ajaran.Data_Tahun_Ajaran')),
            ],
            options={
                'ordering': ['siswa'],
            },
        ),
        migrations.CreateModel(
            name='Data_Pembayaran_SPP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Lunas', 'Lunas'), ('Belum Lunas', 'Belum Lunas')], default='Belum Lunas', max_length=255)),
                ('bulan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Bulan_Pembayaran')),
                ('jenis_pembayaran', models.ForeignKey(limit_choices_to={'jenis_pembayaran': 'SPP'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Jenis_Pembayaran')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siswa.Data_Siswa')),
                ('tahun_ajaran', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tahun_ajaran.Data_Tahun_Ajaran')),
            ],
            options={
                'ordering': ['siswa', 'bulan'],
            },
        ),
        migrations.CreateModel(
            name='Data_Nilai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tugas', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('uts', models.CharField(max_length=3)),
                ('uas', models.CharField(max_length=3)),
                ('mapel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guru.Data_Mapel')),
                ('siswa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='siswa.Data_Siswa')),
                ('tahun_ajaran', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tahun_ajaran.Data_Tahun_Ajaran')),
                ('wali_kelas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guru.Data_Guru')),
            ],
        ),
    ]
