# Generated by Django 3.0.5 on 2020-06-29 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_nilai',
            name='keterampilan',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
