# Generated by Django 3.0.5 on 2020-05-27 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kbm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Siswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nis', models.IntegerField(null=True, unique=True)),
                ('nisn', models.IntegerField(null=True, unique=True)),
                ('nama', models.CharField(max_length=50, null=True)),
                ('tgl_lahir', models.DateField(null=True)),
                ('alamat', models.CharField(blank=True, max_length=255, null=True)),
                ('jenis_kelamin', models.CharField(choices=[('Laki-Laki', 'Laki-Laki'), ('Perempuan', 'Perempuan')], max_length=30, null=True)),
                ('sekolah_sebelumnya', models.CharField(max_length=50)),
                ('foto', models.ImageField(blank=True, default='profil.png', null=True, upload_to='')),
                ('kelas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kbm.Data_Kelas')),
                ('user', models.OneToOneField(blank=True, limit_choices_to={'groups__name': 'siswa'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
