# Generated by Django 3.0.5 on 2020-05-27 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Mapel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kd_mapel', models.CharField(max_length=6, null=True, unique=True)),
                ('nama_mapel', models.CharField(max_length=50, null=True)),
                ('kkm', models.CharField(max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Data_Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.IntegerField(null=True, unique=True)),
                ('nama', models.CharField(max_length=255, null=True)),
                ('tgl_lahir', models.DateField()),
                ('alamat', models.CharField(max_length=255, null=True)),
                ('foto', models.ImageField(blank=True, default='profile.png', null=True, upload_to='')),
                ('mapel', models.ManyToManyField(blank=True, to='guru.Data_Mapel')),
                ('user', models.OneToOneField(limit_choices_to={'groups__name': 'staff_tu'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Data_Guru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.IntegerField(null=True, unique=True)),
                ('nama', models.CharField(max_length=255, null=True)),
                ('tgl_lahir', models.DateField()),
                ('alamat', models.CharField(max_length=255, null=True)),
                ('foto', models.ImageField(blank=True, default='profile.png', null=True, upload_to='')),
                ('mapel', models.ManyToManyField(to='guru.Data_Mapel')),
                ('user', models.OneToOneField(blank=True, limit_choices_to={'groups__name': 'guru'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
