# Generated by Django 3.0.5 on 2020-06-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_mapel',
            name='bobot',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='data_guru',
            name='mapel',
            field=models.ManyToManyField(blank=True, to='guru.Data_Mapel'),
        ),
    ]
