# Generated by Django 3.0.5 on 2020-06-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0002_auto_20200605_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_mapel',
            name='jenis',
            field=models.CharField(choices=[('UMUM', 'UMUM'), ('AP', 'AP'), ('TKJ', 'TKJ')], max_length=10, null=True),
        ),
    ]
