# Generated by Django 3.0.5 on 2020-06-08 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0003_data_mapel_jenis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_guru',
            name='mapel',
        ),
    ]
