# Generated by Django 3.0.5 on 2020-05-27 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tahun_ajaran', '0001_initial'),
        ('guru', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Jurusan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kd_jurusan', models.CharField(max_length=5, null=True)),
                ('jurusan', models.CharField(choices=[('Teknik Komputer Jaringan', 'Teknik Komputer Jaringan'), ('Administrasi Perkantoran', 'Administrasi Perkantoran')], max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Data_Kelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelas', models.CharField(choices=[('X ( Sepuluh )', 'X ( Sepuluh )'), ('XI ( Sebelas )', 'XI ( Sebelas )'), ('XII ( Dua Belas )', 'XII ( Dua Belas )')], max_length=20, null=True)),
                ('ruang', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=3, null=True)),
                ('jurusan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kbm.Data_Jurusan')),
                ('wali_kelas', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guru.Data_Guru')),
            ],
        ),
        migrations.CreateModel(
            name='Data_Jadwal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.CharField(choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ("Jum'at", "Jum'at"), ('Sabtu', 'Sabtu')], max_length=20, null=True)),
                ('jam_mulai', models.TimeField(null=True)),
                ('jam_selesai', models.TimeField(null=True)),
                ('guru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guru.Data_Guru')),
                ('kelas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kbm.Data_Kelas')),
                ('mapel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guru.Data_Mapel')),
                ('tahun_ajaran', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tahun_ajaran.Data_Tahun_Ajaran')),
            ],
            options={
                'ordering': ['-hari', 'jam_mulai'],
            },
        ),
    ]
