# Generated by Django 3.0.5 on 2020-06-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data_jadwal',
            options={'ordering': ['-hari', 'jam']},
        ),
        migrations.RemoveField(
            model_name='data_jadwal',
            name='jam_mulai',
        ),
        migrations.RemoveField(
            model_name='data_jadwal',
            name='jam_selesai',
        ),
        migrations.AddField(
            model_name='data_jadwal',
            name='jam',
            field=models.CharField(choices=[('12.30 - 13.30', '12.30 - 13.30'), ('12.30 - 14.30', '12.30 - 14.30'), ('14.30 - 15.30', '14.30 - 15.30'), ('16.00 - 17.00', '16.00 - 17.00')], max_length=15, null=True),
        ),
    ]
