# Generated by Django 3.0.5 on 2020-06-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbm', '0002_auto_20200608_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_jadwal',
            name='jam',
            field=models.CharField(choices=[('12.30 - 13.30', '12.30 - 13.30'), ('13.30 - 14.30', '13.30 - 14.30'), ('12.30 - 14.30', '12.30 - 14.30'), ('14.30 - 15.30', '14.30 - 15.30'), ('16.00 - 17.00', '16.00 - 17.00')], max_length=15, null=True),
        ),
    ]
