# Generated by Django 3.0.5 on 2020-06-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbm', '0003_auto_20200609_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_jurusan',
            name='jurusan',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
